# Generated by Django 2.1.5 on 2019-03-08 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employees.Designation'),
            preserve_default=False,
        ),
    ]
