# Generated by Django 2.1.5 on 2019-03-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='Designation',
            new_name='designation',
        ),
    ]
