# Generated by Django 2.1.5 on 2019-03-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20190318_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='breakAllowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_month_duration',
            field=models.CharField(max_length=6),
        ),
    ]
