# Generated by Django 2.1.5 on 2019-03-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.IntegerField()),
                ('empName', models.CharField(max_length=100)),
                ('empDept', models.CharField(max_length=30)),
                ('shiftId', models.IntegerField(max_length=3)),
                ('attDay', models.CharField(max_length=10)),
                ('attMonth', models.CharField(max_length=20)),
                ('attYear', models.CharField(max_length=4)),
                ('attDate', models.DateField(max_length=10)),
                ('timeIn', models.CharField(max_length=5)),
                ('timeOut', models.CharField(max_length=5)),
                ('moveOut', models.CharField(max_length=5)),
                ('moveIn', models.CharField(max_length=5)),
                ('duration', models.CharField(max_length=5)),
            ],
        ),
    ]
