# Generated by Django 2.1.5 on 2019-03-18 10:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fna', '0002_auto_20190318_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoansLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.IntegerField()),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('entryDate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.IntegerField()),
                ('empName', models.CharField(max_length=100)),
                ('shiftId', models.IntegerField()),
                ('payMonth', models.CharField(max_length=20)),
                ('payYear', models.CharField(max_length=4)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('hourlyRate', models.IntegerField()),
                ('totalWorkDuration', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('totalPayout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('loan', models.FloatField(default=0)),
                ('netSalary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('paidOff', models.BooleanField(default=False)),
            ],
        ),
    ]
